### ISSUE TITLE
json files question

### ISSUE THREAD

**Issue by AntroFyo** [coding-phoenix-12/LIMMITS25_evaluation#1]
For track1, does the content of teamName_track1_latency_normaliser.json and teamName_track1_latency.json is the same?
I understand the content of teamName_track1_latency_normaliser.json consist of {time_to_first_frame, time_to_last_frame, num_frames}, and i have no idea of the content of teamName_track1_latency.json as it is not introduced in limmits_latency_eval.py.

**Comment by coding-phoenix-12** [comment]
You will have to create the teamName_track1_latency.json on your own. You can use limmits_latency_eval.py. as reference. The code generates the {time_to_first_frame, time_to_last_frame, num_frames} fields by running inference with a smaller reference model. You'll have to run inference using the proposed model and calculate the values as done in limmits_latency_eval.py.

**Comment by aluminumbox** [comment]
> You will have to create the teamName_track1_latency.json on your own. You can use limmits_latency_eval.py. as reference. The code generates the {time_to_first_frame, time_to_last_frame, num_frames} fields by running inference with a smaller reference model. You'll have to run inference using the proposed model and calculate the values as done in limmits_latency_eval.py.

So the difference between teamName_track1_latency.json and teamName_track1_latency_normaliser.json is that, teamName_track1_latency_normaliser.json is created by limmits_latency_eval.py, but teamName_track1_latency.json is created by ourself using same logic according to limmits_latency_eval.py? Thanks

**Comment by coding-phoenix-12** [comment]
Yes.
